apiVersion: v1
kind: Secret
metadata:
  name: llm-secrets
  namespace: browser-platform
type: Opaque
stringData:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: browser-platform-config
  namespace: browser-platform
data:
  NODE_ENV: "production"
  DEBUG: "false"
  BROWSER_HEADLESS: "true"
  BROWSER_TIMEOUT: "30000"
  LLM_PROVIDER: "azure_openai"
  SESSION_TIMEOUT: "1800000"
  SESSION_IDLE_TIMEOUT: "600000"
  SESSION_CLEANUP_DELAY: "120000"
  SESSION_CLEANUP_CHECK_INTERVAL: "60000"
  MAX_SESSIONS: "10"
  MAX_CONCURRENT_SESSIONS: "10"
  AUTO_CLEANUP: "true"
  FORCE_CLEANUP_ON_TASK_COMPLETE: "true"
  LOG_LEVEL: "info"
  MAX_SCREENSHOT_SIZE: "2000000"
  FRAME_RATE: "30"
  COMPRESSION_QUALITY: "80"
  ALLOWED_ORIGINS: "https://your-domain.com,http://localhost:3000"
